name: Linters

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        globs: |
          *.md
    - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log
